name = "rd-paint" # 项目名称
main = "src/index.js"
compatibility_date = "2025-10-26"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NF_PB_KV" # 你的 KV 命名空间的名称
id = "ed0d3d95d909409f8f0f9ba6894f8a1e" # 命名空间的 ID

[[durable_objects.bindings]]
name = "WEBSOCKET_HANDLER"
class_name = "WebSocketHandler"

[unsafe]
allow = ["rpc"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHandler"]

route = "pb.5.3.f.7.a.2.8.f.0.7.4.0.1.0.0.2.ip6.arpa/*" # 替换成你的域名
